### ISSUE TITLE
var Gpio = require('pigpio').Gpio is undefined

### ISSUE THREAD

**Issue by tralves** [fivdi/pigpio#1]
I can't get this to work. I am trying the led example in the readme.md, but the var Gpio is always undefined.

```
$ node -v
v0.12.6
$ gcc -v
gcc version 4.9.2 (Raspbian 4.9.2-10) 
````

**Comment by fivdi** [comment]
Yes, that's because the master branch on github is ahead of what has been published on npm. I'll publish a new version soon so that they are in sync. Until then, use the documentation here https://github.com/fivdi/pigpio/tree/v0.0.8

**Comment by tralves** [comment]
Thanks! It works now.

**Comment by fivdi** [comment]
That's good news :)
