### ISSUE TITLE
Enhanced : Processing a GPI event (rasing, falling or edge) by interrupt

### ISSUE THREAD

**Issue by yboujraf** [fivdi/pigpio#101]
Dear @fivdi 

I have a use case and I 'd like to check if it could be an enhanced functionality in your repository.

## GPI - Interrupt enabled (falling , rising or edge) processing

![image](https://user-images.githubusercontent.com/6151258/75087040-afdab980-553b-11ea-8918-9f8df6905142.png)

![image](https://user-images.githubusercontent.com/6151258/75087065-0fd16000-553c-11ea-9e5f-1582355796ca.png)

### Use case

1. I receive a pulse from a device
2. I need to detect the pulse. that means I need to enable GPI with interrupt (edge)
3. the rising edge could be delayed. Tin = x ms but could be 0
4. the falling edge could be delayed. Tout = x ms but could be 0
5. At the falling edge, I need to delay it. P2 = x ms but could be 0.

Finally I need to have :

- Delay the rising edge => Tin >= 0 ms
- Delay the falling edge => Tout + P2 >= 0 ms

I need this functionality per GPI.

What do you think ?

Best Regards
Youssef

**Comment by fivdi** [comment]
What have you tried and what were the problems?

**Comment by fivdi** [comment]
I don't see any reason to enhance pigpio here.
