### ISSUE TITLE
Does pigpio support compute module 3 ?

### ISSUE THREAD

**Issue by jinyistudio** [fivdi/pigpio#118]
Does pigpio support compute module 3 ?

**Comment by jinyistudio** [comment]
1. CM3 is ok. node .js with sudo
2. I need as root when i porting to NODE-RED as node. Do you know how to run as root in the NODE-RED ?

**Comment by fivdi** [comment]
>1. CM3 is ok.

Thank you for confirming this to be the case.

>node .js with sudo

Yes, this is correct. `sudo` is required by the underlying pigpio C library.

>2. I need as root when i porting to NODE-RED as node. Do you know how to run as root in the NODE-RED ? 

Unfortunately I'm not familiar with Node-RED. I'd suggest asking this question at the Node-RED forum (https://discourse.nodered.org/)

**Comment by fivdi** [comment]
There is no actionable for pigpio here so I'll go ahead and close the issue.
