### ISSUE TITLE
difference between pigpio and pi-blaster?

### ISSUE THREAD

**Issue by The-Alchemist** [fivdi/pigpio#12]
I was looking at https://github.com/sarfata/pi-blaster, and I was wondering if there were differences, if any.

I'm not that tech savvy when it comes to hardware, PWM, DMA, etc.

Thanks!

**Comment by fivdi** [comment]
The ability of pigpio and pi-blaster to enable PWM on any GPIO are based on the same underlying technique. The original work was done by Richard Hirst with the ServoBlaster kernel driver. See https://github.com/richardghirst/PiBits.
