### ISSUE TITLE
Setting output direction

### ISSUE THREAD

**Issue by 13** [fivdi/pigpio#123]
I'm running a relay with the following [onoff library](https://github.com/fivdi/onoff#activelow) initialization:

`var relay = new Gpio(4, 'high', {activeLow:true})`

Exists there a pigpio equivalent?

**Comment by fivdi** [comment]
There is no exact equivalent but it should be possible to implement the equivalent using the functionality provided by pigpio. What have you tried and what were the issues?

**Comment by 13** [comment]
Resolved by inverting the logic
```
function setRelay(gpio,state) {
  if (state){
    gpio.digitalWrite(!true)
  } else {
    gpio.digitalWrite(!false)
  }
}
```
