### ISSUE TITLE
Permission to pi user for hardware peripherals - how to make it work?

### ISSUE THREAD

**Issue by lucianobustos** [fivdi/pigpio#129]
Hello I'm using this library but I can't run it without sudo command (as pi user). 
Which is the correct way to grant PI user permission to run pigpio inside node without sudo??

I've checked permisios, libs and I think the user has permission because, for example your fivdi/onoff lib works.
Is there any particular condition to meet for the pi user in order to run pigpio? 

I'm running my app with `pm2  node bin/ww` where www is the js main server file.

> I was checking these 2 pages algo.
> https://roboticsbackend.com/raspberry-pi-hardware-permissions/#GPIOs
> https://www.raspberrypi.org/forums/viewtopic.php?t=8999

Thanks in advance!

**Comment by lucianobustos** [comment]
I'm using pm2 to run node.

`sudo chmod -R 775 bin`  (where my start script is) solve the issue.

Maybe this could be somewhere in the docu.

**Comment by fivdi** [comment]
I'm afraid it's not possible to run an app that uses the pigpio Node.js module without root permissions. The pigpio Node.js module is a wrapper for the [pigpio C library](https://github.com/joan2937/pigpio) and the C library requires root permissions.

**Comment by fivdi** [comment]
I'll go ahead and close this as there is no TODO for pigpio.
