### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by Canees** [fivdi/pigpio#137]
Hello moderator:
Can you come up with a use case for electronic speed controller? I am a novice do not understand how PWM is generated, tried a lot of methods

**Comment by fivdi** [comment]
> I am a novice do not understand how PWM is generated, tried a lot of methods

What have you tried and what were the problems?

**Comment by Canees** [comment]
> > I am a novice do not understand how PWM is generated, tried a lot of methods
> 
> What have you tried and what were the problems?

Hi, sorry for taking so long to reply：
for example:
  let speed = 0
  let timer = setInterval(() => {
              speed++
              if (speed > 3) {
                  this.motor.servoWrite(Math.round(3 * 1000 / 7 + 1000))
                  clearInterval(timer)
                  console.log('End of the calibration....')
              } else {
                  this.motor.servoWrite(Math.round(speed * 1000 / 7 + 1000))
                  console.log('In the calibration：', speed)
              }
      }, 2000);
  I am referring to the steering gear example given in the document，But using PWM for testing is useless, although I know it is used for leds。
  The above example is very troublesome because the median value of each electrical modulation is different and cannot be automatically calibrated. Do you have any good suggestions?
