### ISSUE TITLE
Error: EINVAL, Invalid argument

### ISSUE THREAD

**Issue by samwelkinuthia** [fivdi/pigpio#139]
I am using pigpio for servo control and i get the following error

![Screenshot from 2021-11-18 16-53-14](https://user-images.githubusercontent.com/27720313/142429470-3816f94d-af7b-478f-b40f-1dd1d73029df.png)

**Comment by fivdi** [comment]
In your code, on line 32 of server.js, there is a call to `servoWrite`. As described [here in the documentation](https://github.com/fivdi/pigpio/blob/master/doc/gpio.md#servowritepulsewidth), the value passed to `servoWrite` must be an unsigned integer, that is, the value passed to `servoWrite` must be 0 or a number in the range 500 through 2500. Is your code calling `servoWrite` correctly? It looks like it isn't.

**Comment by samwelkinuthia** [comment]
Thank you! I was passing it incorrectly.
