### ISSUE TITLE
 pigpio.gpioInitialise() in pi 4B

### ISSUE THREAD

**Issue by alanezze** [fivdi/pigpio#146]
hello, I'm trying to run by npm and node 14 from a raspberry and throws this error

```
sevnt@raspberrypi:~/Documents/wiegand-rasberry $ sudo node send-wiegand.js 
2022-08-27 17:48:24 initInitialise: Can't lock /var/run/pigpio.pid
/home/sevnt/Documents/wiegand-rasberry/node_modules/pigpio/pigpio.js:54
    pigpio.gpioInitialise();
           ^

Error: pigpio error -1 in gpioInitialise
    at initializePigpio (/home/sevnt/Documents/wiegand-rasberry/node_modules/pigpio/pigpio.js:54:12)
```

Version NodeJs
v14.20.0

Version piGpio
79

check the previous problems resolved and none have worked

the only difference is that when checking the version of linux it is 00000D00
instead of C,
It is a newly purchased latest model raspberry with the latest and updated raspbian OS

**Comment by nexuspcs** [comment]
run this command, it worked for me: `sudo killall pigpiod`

**Comment by nexuspcs** [comment]
and then try to run this command, it may not work though: `sudo killall pigpio`

**Comment by nexuspcs** [comment]
let me know how you go, I have a lot of issues as well

**Comment by alanezze** [comment]
@nexuspcs 
Hello, I already tried restarting the PIGPIO daemon, and it's still the same

**Comment by nexuspcs** [comment]
so you have tried: `sudo killall pigpiod`
maybe try this:; http://abyz.me.uk/rpi/pigpio/faq.html#Cant_initialise_pigpio_library

**Comment by nexuspcs** [comment]
As this link describes run these commands:: 
- `cat /var/run/pigpio.pid` 
- `sudo kill -9 pid` (replace 'pid' with the id/pid number of the process printed out in the 1st command)

**Comment by nexuspcs** [comment]
If this does not work, try this commands:

`sudo rm /var/run/pigpio.pid`

**Comment by nexuspcs** [comment]
And then restart daemon: `sudo pigpiod`
And then try your script, and then if it still not works, try to kill: `sudo killall pigpiod` and `sudo killall pigpio`

**Comment by nexuspcs** [comment]
I had this issue before, and it is what worked for me.   ....

**Comment by nexuspcs** [comment]
#145 
This happened to me in this issue.

**Comment by alanezze** [comment]
It worked but with this sequence:

`sudo pigpiod`
`cat /var/run/pigpio.pid`
(save number)
`sudo pigpiod`
`sudo rm /var/run/pigpio.pid`
`sudo killall pigpiod`

delete nodemodules and
`npm start`


muchas gracias por tu ayuda @nexuspcs

**Comment by nexuspcs** [comment]
You are most welcome, I had similar issues, so I am glad that I could helps you !
