### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by Raqbit** [fivdi/pigpio#16]
Error: http://pastebin.com/ztq29Ekb

**Node version**: v7.7.0 (Installed manually)

**Pi**: Using the new Pi Zero W :)

Getting this error when trying to install this package. ~It might be because of my non-ordinary node install method.~ I did notice that I didn't see the "you don't have to install pigpio as it's included in raspbian" sentence, so I did install pigpio. I don't think that causes this problem.

**Edit:** I cleaned my Node install, and used NVM to do a new install, but the same problem occurs.

**Comment by fivdi** [comment]
Very nice, the newest of software on the newest of hardware :)

This is a Node.js issue. V7.0.0 is broken. See https://github.com/nodejs/nan/issues/644 for further information. 

It looks like you'll have to downgraded to an older version of Node.is or wait for V7.0.1.

**Comment by fivdi** [comment]
The corresponding Node.js issue is https://github.com/nodejs/node/issues/11628

**Comment by fivdi** [comment]
Node.js v7.7.1 has been released so this should no longer be an issue

**Comment by Raqbit** [comment]
Oh right, I should've noticed that it wasn't the latest LTS >.< Thanks for the help anyways!
