### ISSUE TITLE
Java Native Interface sigHandler: Unhandled signal 11, terminating

### ISSUE THREAD

**Issue by LucosidE** [fivdi/pigpio#24]
When using pigpio in Java through JNI the program terminates with 

sigHandler: Unhandled signal 11, terminating

this happens when using interrupt functions such as gpioSetAlertFunc or gpioSetISTFunc even if these functions do absolutely nothing. 

This might be a JNI issue. If anyone has any ideas on how to use pigpio interrupts in Java I would greatly appreciate any suggestions. 

I updated to latest java
java version "1.8.0_131"

```
void interrupt_s(int gpio, int level, uint32_t tick)
{
   /*
      Callback does nothing
   */
}


JNIEXPORT jlong JNICALL Java_pigpioTest
  (JNIEnv *env, jobject obj, jint pin)
{
	//Initialize PIGPIO library
	if (gpioInitialise() < 0) {
		return 0;
	}
        // Set a single pin as input
	gpioSetMode(pin, PI_INPUT);
	gpioSetPullUpDown(pin, PI_PUD_DOWN);
	   /* monitor pin level changes */
	gpioSetAlertFunc(pin, interrupt_s);
	return 1;
}
```

The above runs for a while and then the sigHandler: Unhandled signal 11, terminating error happens.

**Comment by fivdi** [comment]
I think this issues was created in the wrong repo. It should probably have been created at https://github.com/joan2937/pigpio

This repo is a JavaScript repo for Node.js.
