### ISSUE TITLE
Getting multiple events when button pressed

### ISSUE THREAD

**Issue by ScottChapman** [fivdi/pigpio#26]
I am using a membrane button, one lead to ground, other to GPIO 12. Code below. Problem is that I occasionally get multiple events when I click the button...

```
var Gpio = require('pigpio').Gpio;
var button1 = new Gpio(12, {
    mode: Gpio.INPUT,
    pullUpDown: Gpio.PUD_UP,
    edge: Gpio.FALLING_EDGE
  });

button1.on('interrupt', function (level) {
        if (level === 0) {
                console.log("Button1 Pressed!");
        }
});
```

**Comment by fivdi** [comment]
This is button bounce. There's an article describing the topic [here](https://www.allaboutcircuits.com/technical-articles/switch-bounce-how-to-deal-with-it/). To resolve the issue with software consider using the [lodash debounce function](https://lodash.com/docs/#debounce).
