### ISSUE TITLE
Calling PIGPIO from multiple task failed

### ISSUE THREAD

**Issue by bahamut657** [fivdi/pigpio#27]
I have two child processes, each one control specific PIN through pigpio.
when the second subtask starts, i obtain this error 
2017-07-08 15:02:10 initInitialise: Can't lock /var/run/pigpio.pid
~/node_modules/pigpio/pigpio.js:11
    pigpio.gpioInitialise();
           ^

Error: pigpio error -1 in gpioInitialise
    at initializePigpio (~/node_modules/pigpio/pigpio.js:11:12)
    at new Gpio (~/node_modules/pigpio/pigpio.js:25:3)

Could be possible to use pigpio from multiple task at the moment?
Why this limitation? I miss something?

**Comment by fivdi** [comment]
I'm afraid that this is a limitation of the [pigpio C library](https://github.com/joan2937/pigpio) which is out of my control.

**Comment by fivdi** [comment]
This should be documented in the readme.

**Comment by fivdi** [comment]
The readme now has a [limitations section](https://github.com/fivdi/pigpio#limitations) which documents that the pigpio Node.js package can only be used by a single running process. This is a limitation of the pigpio C library.

@bahamut657 Thank you for reporting this issue.
