### ISSUE TITLE
Mocking PiGPIO

### ISSUE THREAD

**Issue by deepsyx** [fivdi/pigpio#29]
Hey guys!
I really enjoy using this lib, however I didn't find a proper way to mock the pigpio on my local machine, so I wrote a simple lib, that copies all methods from this one and prints to console one is invoked.

https://github.com/deepsyx/pigpio-mock

Thought it might be useful :)

**Comment by fivdi** [comment]
@deepsyx Nice :tada:

A link to the [pigpio-mock](https://github.com/deepsyx/pigpio-mock) library has been added to the [Related packages](https://github.com/fivdi/pigpio#related-packages) section of the readme. This should help people find it.

Thanks :+1:
