### ISSUE TITLE
Bit Banging Operations

### ISSUE THREAD

**Issue by JoelDapello** [fivdi/pigpio#3]
Hello! Awesome work with this library. I'm wondering if you have plans or interest in supporting the bit banging operations capable with the pigpio c library? 

Specifically, I'm interested in the TX associated functions

```
gpioWaveClear
gpioWaveAddNew
gpioWaveAddGeneric
gpioWaveAddSerial   
gpioWaveCreate  
gpioWaveDelete  
gpioWaveTxSend
gpioWaveTxBusy
```

and the RX associated functions

```
gpioSerialReadOpen
gpioSerialRead
gpioSerialReadClose
```

If you are not planning to add these, perhaps I could assist in integrating them?

**Comment by fivdi** [comment]
I'm interested in supporting as much of the pigpio C library as possible :). If adding support for the bit banging operations is something that you would like to do then feel free to do so.

**Comment by fivdi** [comment]
I've decided against adding the bit banging operations.
