### ISSUE TITLE
GPIO Cleanup

### ISSUE THREAD

**Issue by karthikbnd** [fivdi/pigpio#5]
Hai,
Can i know how to clean the GPIO using your library

**Comment by fivdi** [comment]
What do you mean by "clean"?

**Comment by karthikbnd** [comment]
at the end of program to clear gpio pins

**Comment by fivdi** [comment]
Do you mean to set the value of GPIOs configured as outputs to 0 before the program terminates?

If so, the [digitalWrite](https://github.com/fivdi/pigpio/blob/master/doc/gpio.md#digitalwritelevel) method can be called for the corresponding GPIOs before the program terminates. Calling the digitalWrite(0) for a GPIO will set the value of the GPIO to 0.

**Comment by karthikbnd** [comment]
thanks
