### ISSUE TITLE
Frequency and dutycycle for brushless motor

### ISSUE THREAD

**Issue by malhar-quickwork** [fivdi/pigpio#57]
So I'm trying to run a brushless motor with pigpio. At first the motor didn't move at all just beeped at intervals so I figured I'd try this command.
`pigs s 4 1200 `
and the motor starts spinning at value of 1300.

So in my code I set pwmFrequency at 500 and motor starts spinning at value 166 for dutycycle. 
Also in this case, the motor jerks at some intervals. 

Can anyone help me find a frequency so it can run smoothly and I can increase or decrease dutycycles?
I'm a total newbie at the physics of this so can anyone explain how to find a smooth config

**Comment by bahamut657** [comment]
Look at http://abyz.me.uk/rpi/pigpio/code/servo_demo.zip.
This is a C++ example that generates servo pulses on one or more GPIO writter by the author of pigpio.
Contact private if need help
