### ISSUE TITLE
Script hanging and child_process.exec callback never called

### ISSUE THREAD

**Issue by LukaszTlalka** [fivdi/pigpio#66]
I encountered a problem when trying to execute a child process that takes a bit more time to execute with pigpio. Consider this code: 

```js
const pigpio = require('pigpio');
const { exec } = require('child_process');

exec('sleep 3', () => {
    console.log('never reached');
});

pigpio.initialize();
pigpio.terminate();
```
pigpio version: 1.1.4

I did read the Limitation section. Can this also be related to the fact that there can be only one signal handler in Linux (refs: #10)?

**Comment by fivdi** [comment]
Your assumption that the issue is related to signal handlers appears to be correct. What does work is something like this:
```js
const pigpio = require('pigpio');
const Gpio = pigpio.Gpio;
const { exec } = require('child_process');

pigpio.initialize();

exec('sleep 3', () => {
    console.log('reached');
    led.digitalWrite(0);
    pigpio.terminate();
});

const led = new Gpio(17, {mode: Gpio.OUTPUT});
led.digitalWrite(1);
```
or something like this:
```js
const pigpio = require('pigpio');
const Gpio = pigpio.Gpio;
const { exec } = require('child_process');

pigpio.initialize();

exec('sleep 3', () => {
    console.log('reached');
});

const led = new Gpio(17, {mode: Gpio.OUTPUT});

led.digitalWrite(1);

setTimeout(() => {
  led.digitalWrite(0);
  pigpio.terminate();
}, 1000);
```
The trick is to call `pigpio.initialize()` before any signal handlers are registered by JavaScript code and to call `pigpio.terminate()` at the appropriate time.
