### ISSUE TITLE
typo issue in TypeScript

### ISSUE THREAD

**Issue by park012241** [fivdi/pigpio#71]
https://gist.github.com/d7024a585d71794b87050c5856237742

![image](https://user-images.githubusercontent.com/12793256/52564758-4f08a380-2e48-11e9-8c02-a624822fdf7c.png)

There is typo error in TS description (.d.ts) file.
It shuld be "level", but it is "levle" in @types/pigpio index.d.ts:75 and 77

**Comment by fivdi** [comment]
The TS description file isn't part of this repository. As far as I know it's part of https://github.com/DefinitelyTyped/DefinitelyTyped. I wasn't aware that it was available. I'd suggest creating at PR at that repository with a fix.

**Comment by park012241** [comment]
OK, I will!
Thanks!

**Comment by fivdi** [comment]
Excellent :)
