### ISSUE TITLE
How to read Wiegand?

### ISSUE THREAD

**Issue by 8483** [fivdi/pigpio#78]
Can someone please explain how the code should look like to read Wiegand data?

**Comment by fivdi** [comment]
I'd suggest taking a look at the [WIEGAND_CODE](https://github.com/joan2937/pigpio/tree/master/EXAMPLES/C/WIEGAND_CODE) example that is implemented in C and is part of the pigpio C library. Use this example for ideas on how to implement the code in JavaScript.

**Comment by 8483** [comment]
Thank you for the advice. I am way out of my league here, but I will do my best.  

It would be cool to have this as part of the library.
