### ISSUE TITLE
any way to use with the pigpio daemon?

### ISSUE THREAD

**Issue by BryanCrotaz** [fivdi/pigpio#86]
I'm using this from a node.js web server. While I can give the server root access for testing, this isn't a good idea for deployment!

Is there a way to direct this library at the daemon, or is there a recommendation for another way to avoid giving the main UI root access?

I'm using the `Gpio.pwmWrite` and `Gpio.pwmRange` methods.

**Comment by fivdi** [comment]
I'm afraid not. The pigpio C library can only be used by one process at the same time and the pigpio C library requires root privileges.

**Comment by BryanCrotaz** [comment]
Which is why the daemon exists. What would need to be added to make this work with the daemon?

**Comment by fivdi** [comment]
That's not entirety true. The pigpio C library offers more functionality than the deamon and is extremely fast. The pigpio Node.js module was created to provide access to the additional functionality but also for the direct fast access to hardware peripherals.

**Comment by fivdi** [comment]
Consider using a Node.js module that communicates with the daemon or implement code to do this for pwmWrite and pwmRange. I don't want to modify this module to use the daemon rather than the C library.

**Comment by fivdi** [comment]
There's no TODO for pigpio here so I'll go ahead and close the issue.

**Comment by BryanCrotaz** [comment]
Todo: support choice of daemon or direct C attachment through a single interface. 

Either with two different classes which have the same interface, or with a Strategy pattern and a switch in the constructor.
