### ISSUE TITLE
At the moment both the pigpio Node.js module and the pigpio C library are experimental on the Raspberry Pi 4 Model B.

### ISSUE THREAD

**Issue by yboujraf** [fivdi/pigpio#91]
Dear @fivdi 

I have a raspberry PI4 4GB with raspian.

Is there a risk to use it with you library ?

Best Regards,
Youssef

**Comment by fivdi** [comment]
I'm not aware of any risks and everything I have tried with the pigpio Node.js module on a Pi 4 worked for me.

The pigpio Node.js module is experimental as the pigpio C library is experimental. See [here](https://github.com/joan2937/pigpio#pigpio). The corresponding pigpio C library issue is [here](https://github.com/joan2937/pigpio/issues/278).

**Comment by yboujraf** [comment]
Dear @fivdi 

Thanks a lot for your quick reply

I appreciate it so much

Have a nice day.
Youssef

**Comment by fivdi** [comment]
> Have a nice day.

You too.
